# Generated by Django 5.0.1 on 2024-02-01 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuItem',
            new_name='TreeMenu',
        ),
    ]
