# Generated by Django 5.0.1 on 2024-02-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu_app', '0002_rename_menuitem_treemenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='treemenu',
            name='name',
            field=models.CharField(default='main_menu', max_length=50),
            preserve_default=False,
        ),
    ]
