# Generated by Django 5.0.1 on 2024-02-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu_app', '0003_treemenu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='treemenu',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, to='tree_menu_app.treemenu'),
        ),
    ]
