# Generated by Django 5.0.1 on 2024-02-01 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu_app', '0004_treemenu_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treemenu',
            name='children',
        ),
    ]
