# Generated by Django 5.0.1 on 2024-02-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu_app', '0005_remove_treemenu_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treemenu',
            name='parent',
        ),
        migrations.AddField(
            model_name='treemenu',
            name='child',
            field=models.ManyToManyField(blank=True, null=True, to='tree_menu_app.treemenu'),
        ),
    ]
