# Generated by Django 5.0.1 on 2024-02-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu_app', '0006_remove_treemenu_parent_treemenu_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treemenu',
            name='child',
            field=models.ManyToManyField(null=True, to='tree_menu_app.treemenu'),
        ),
    ]
