# Generated by Django 5.0.1 on 2024-02-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu_app', '0008_remove_treemenu_child_treemenu_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='treemenu',
            name='child',
            field=models.ManyToManyField(blank=True, to='tree_menu_app.treemenu'),
        ),
    ]
