# Generated by Django 5.0.1 on 2024-02-01 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu_app', '0009_treemenu_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treemenu',
            name='child',
        ),
    ]
