# Generated by Django 5.0.1 on 2024-02-01 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu_app', '0010_remove_treemenu_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treemenu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tree_menu_app.treemenu'),
        ),
    ]
